<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $department = array(
            array('id_department' => '151','department_name' => ' Аварийно-диспетчерская служба'),
            array('id_department' => '18','department_name' => '1 отдел'),
            array('id_department' => '79','department_name' => 'Агропромышленный факультет'),
            array('id_department' => '20','department_name' => 'Аттестационный отдел'),
            array('id_department' => '158','department_name' => 'Багаевский филиал'),
            array('id_department' => '159','department_name' => 'Багаевский филиал'),
            array('id_department' => '23','department_name' => 'Военный институт'),
            array('id_department' => '136','department_name' => 'Волонтерский центр'),
            array('id_department' => '34','department_name' => 'Высшая школа управления'),
            array('id_department' => '128','department_name' => 'Геологический кабинет'),
            array('id_department' => '180','department_name' => 'Городская поликлиника № 1'),
            array('id_department' => '6','department_name' => 'Деканат геологии '),
            array('id_department' => '1','department_name' => 'Деканат ФИОП'),
            array('id_department' => '2','department_name' => 'Деканат ФИТУ'),
            array('id_department' => '134','department_name' => 'Департамент молодежной политики и довузовской подготовки'),
            array('id_department' => '21','department_name' => 'Департамент по военному образованию и делам казачества'),
            array('id_department' => '22','department_name' => 'Департамент по военному образованию и делам казачества'),
            array('id_department' => '149','department_name' => 'Департамент по развитию имущественного комплекса'),
            array('id_department' => '114','department_name' => 'Департамент цифровизации инженерной деятельности'),
            array('id_department' => '164','department_name' => 'Департамент экономики и финансов'),
            array('id_department' => '135','department_name' => 'Детский технопарк “Звезда”'),
            array('id_department' => '126','department_name' => 'Журнал «Известия ВУЗов. Северо-Кавказский регион. Серия Технические науки»'),
            array('id_department' => '125','department_name' => 'Журнал «Электромеханика»'),
            array('id_department' => '171','department_name' => 'Издательский дом "Политехник" '),
            array('id_department' => '138','department_name' => 'Институт дополнительного образования'),
            array('id_department' => '32','department_name' => 'Институт международного образования'),
            array('id_department' => '35','department_name' => 'Институт фундаментального инженерного образования'),
            array('id_department' => '173','department_name' => 'Испытательная лаборатория'),
            array('id_department' => '24','department_name' => 'Кафедра "Информационная безопасность"'),
            array('id_department' => '38','department_name' => 'Кафедра "Общеинженерные дисциплины"'),
            array('id_department' => '25','department_name' => 'Кафедра "Физическое воспитание и спорт"'),
            array('id_department' => '81','department_name' => 'Кафедра «Автоматизация и роботизация агропромышленного комплекса и биосистемный инжиниринг»'),
            array('id_department' => '52','department_name' => 'Кафедра «Автоматика и Телемеханика»'),
            array('id_department' => '55','department_name' => 'Кафедра «Автомобили и транспортно-технологические комплексы»'),
            array('id_department' => '62','department_name' => 'Кафедра «Архитектура и дизайн»'),
            array('id_department' => '60','department_name' => 'Кафедра «Водное хозяйство, инженерные сети и защита окружающей среды»'),
            array('id_department' => '80','department_name' => 'Кафедра «Возобновляемая и малая энергетика»'),
            array('id_department' => '36','department_name' => 'Кафедра «Высшая математика»'),
            array('id_department' => '83','department_name' => 'Кафедра «Гидротехнические сооружения и гидравлика»'),
            array('id_department' => '76','department_name' => 'Кафедра «Горное дело»'),
            array('id_department' => '33','department_name' => 'Кафедра «Иностранные языки»'),
            array('id_department' => '37','department_name' => 'Кафедра «Информатика, инженерная и компьютерная графика» '),
            array('id_department' => '53','department_name' => 'Кафедра «Информационные и измерительные системы и технологии»'),
            array('id_department' => '84','department_name' => 'Кафедра «Информационные системы и технологии в агропромышленном комплексе»'),
            array('id_department' => '56','department_name' => 'Кафедра «Международные логистические системы и комплексы»'),
            array('id_department' => '74','department_name' => 'Кафедра «Мехатроника и гидропневмоавтоматика»'),
            array('id_department' => '78','department_name' => 'Кафедра «Нефтегазовые техника и технологии»'),
            array('id_department' => '64','department_name' => 'Кафедра «Общая химия и технология силикатов»'),
            array('id_department' => '82','department_name' => 'Кафедра «Переработка и упаковка сельскохозяйственной продукции»'),
            array('id_department' => '77','department_name' => 'Кафедра «Прикладная геология»'),
            array('id_department' => '50','department_name' => 'Кафедра «Прикладная математика»'),
            array('id_department' => '51','department_name' => 'Кафедра «Программное обеспечение вычислительной техники»'),
            array('id_department' => '46','department_name' => 'Кафедра «Производственный и инновационный менеджмент»'),
            array('id_department' => '61','department_name' => 'Кафедра «Промышленное, гражданское строительство, геотехника и фундаментостроение»'),
            array('id_department' => '47','department_name' => 'Кафедра «Публично-правовые дисциплины»'),
            array('id_department' => '44','department_name' => 'Кафедра «Социология и психология»'),
            array('id_department' => '66','department_name' => 'Кафедра «Стандартизация, сертификация и управление качеством»'),
            array('id_department' => '69','department_name' => 'Кафедра «Теоретическая электротехника и электрооборудование»'),
            array('id_department' => '42','department_name' => 'Кафедра «Теория государства и права и отечественная история»'),
            array('id_department' => '70','department_name' => 'Кафедра «Тепловые электрические станции и теплотехника»'),
            array('id_department' => '58','department_name' => 'Кафедра «Технологические машины и оборудование»'),
            array('id_department' => '57','department_name' => 'Кафедра «Технология машиностроения»'),
            array('id_department' => '45','department_name' => 'Кафедра «Управление социальными и экономическими системами»'),
            array('id_department' => '39','department_name' => 'Кафедра «Физика и электроника»'),
            array('id_department' => '43','department_name' => 'Кафедра «Философия и право»'),
            array('id_department' => '65','department_name' => 'Кафедра «Химические технологии»'),
            array('id_department' => '68','department_name' => 'Кафедра «Электрические станции и электроэнергетические системы»'),
            array('id_department' => '72','department_name' => 'Кафедра «Электромеханика и электрические аппараты»'),
            array('id_department' => '73','department_name' => 'Кафедра «Электроснабжение и электропривод»'),
            array('id_department' => '48','department_name' => 'Кафедра «Юриспруденция»'),
            array('id_department' => '8','department_name' => 'Кафедра АиТ'),
            array('id_department' => '10','department_name' => 'Кафедра НГ'),
            array('id_department' => '5','department_name' => 'Кафедра ПОВТ'),
            array('id_department' => '7','department_name' => 'Кафедра ТМ'),
            array('id_department' => '161','department_name' => 'Комбинат студенческого питания  "Архимед"'),
            array('id_department' => '167','department_name' => 'Контрактная служба'),
            array('id_department' => '166','department_name' => 'Культурно-образовательный центр "Дом ученых и студентов"'),
            array('id_department' => '139','department_name' => 'Межотраслевой региональный центр повышения квалификации и профессиональной подготовки специалистов'),
            array('id_department' => '140','department_name' => 'Межотраслевой региональный центр повышения квалификации и профессиональной подготовки специалистов'),
            array('id_department' => '141','department_name' => 'Межотраслевой региональный центр повышения квалификации и профессиональной подготовки специалистов'),
            array('id_department' => '54','department_name' => 'Механический факультет'),
            array('id_department' => '94','department_name' => 'Научно-исследовательские институты'),
            array('id_department' => '93','department_name' => 'Научно-образовательные центры'),
            array('id_department' => '121','department_name' => 'Научно-техническая библиотека'),
            array('id_department' => '28','department_name' => 'Научно-технический совет'),
            array('id_department' => '98','department_name' => 'НИИ "Автоматика"'),
            array('id_department' => '102','department_name' => 'НИИ "Водоснабжение и водоотведение"'),
            array('id_department' => '96','department_name' => 'НИИ "Вычислительные, информационные и управляющие системы"'),
            array('id_department' => '97','department_name' => 'НИИ "Вычислительные, информационные и управляющие системы"'),
            array('id_department' => '27','department_name' => 'НИИ "История казачества и развития казачьих регионов"'),
            array('id_department' => '100','department_name' => 'НИИ "Нанотехнологии и новые материалы"'),
            array('id_department' => '101','department_name' => 'НИИ "Строительные технологии"'),
            array('id_department' => '99','department_name' => 'НИИ "Транспортные системы и комплексы"'),
            array('id_department' => '95','department_name' => 'НИИ "Электромеханика"'),
            array('id_department' => '103','department_name' => 'НИИ "Энергетики"'),
            array('id_department' => '105','department_name' => 'НИЦ "Материаловедение"'),
            array('id_department' => '106','department_name' => 'НИЦ "Транспортная безопасность"'),
            array('id_department' => '115','department_name' => 'НовоЦНИТ'),
            array('id_department' => '40','department_name' => 'Новочеркасский политехнический колледж'),
            array('id_department' => '175','department_name' => 'Общественные организации'),
            array('id_department' => '108','department_name' => 'ОКТБ "Старт"'),
            array('id_department' => '179','department_name' => 'ООО "Курьер"'),
            array('id_department' => '15','department_name' => 'Организационный отдел'),
            array('id_department' => '118','department_name' => 'Отдел'),
            array('id_department' => '113','department_name' => 'Отдел аспирантуры и докторантуры'),
            array('id_department' => '170','department_name' => 'Отдел внутреннего финансового контроля'),
            array('id_department' => '172','department_name' => 'Отдел гражданской обороны и охраны труда'),
            array('id_department' => '16','department_name' => 'Отдел делопроизводства'),
            array('id_department' => '123','department_name' => 'Отдел интеллектуальной собственности'),
            array('id_department' => '110','department_name' => 'Отдел капитального строительства'),
            array('id_department' => '168','department_name' => 'Отдел материально-технического снабжения'),
            array('id_department' => '119','department_name' => 'Отдел мониторинга качества образования'),
            array('id_department' => '174','department_name' => 'Отдел обеспечения режима'),
            array('id_department' => '169','department_name' => 'Отдел осуществления закупок'),
            array('id_department' => '132','department_name' => 'Отдел по развитию инфраструктуры инклюзивного образования'),
            array('id_department' => '156','department_name' => 'Отдел проектно-сметной документации и контроля'),
            array('id_department' => '117','department_name' => 'Отдел телеманики и телекоммуникаций'),
            array('id_department' => '116','department_name' => 'Отдел технических систем связи'),
            array('id_department' => '92','department_name' => 'Отдел технического контроля, метрологии и стандартизации'),
            array('id_department' => '19','department_name' => 'Первый проректор'),
            array('id_department' => '11','department_name' => 'Подразделение '),
            array('id_department' => '29','department_name' => 'Президиум диссертационных советов'),
            array('id_department' => '133','department_name' => 'Пресс-служба'),
            array('id_department' => '86','department_name' => 'Проректор по инновационной деятельности'),
            array('id_department' => '109','department_name' => 'Проректор по капитальному строительству'),
            array('id_department' => '111','department_name' => 'Проректор по научной работе и стратегическому развитию'),
            array('id_department' => '30','department_name' => 'Проректор по образовательной деятельности'),
            array('id_department' => '129','department_name' => 'Проректор по социальной политике и взаимодействию с работодателями'),
            array('id_department' => '148','department_name' => 'Проректор по финансово -экономической деятельности и развитию имущественного комплекса'),
            array('id_department' => '176','department_name' => 'Профком сотрудников'),
            array('id_department' => '124','department_name' => 'Редакции журналов'),
            array('id_department' => '122','department_name' => 'Редакционно-издательский отдел'),
            array('id_department' => '12','department_name' => 'Ректор'),
            array('id_department' => '160','department_name' => 'Санаторий-профилакторий'),
            array('id_department' => '137','department_name' => 'Специализированная двухгодичная школа'),
            array('id_department' => '26','department_name' => 'Спортивный клуб'),
            array('id_department' => '162','department_name' => 'Спортивный комплекс'),
            array('id_department' => '178','department_name' => 'Сторонние организации'),
            array('id_department' => '59','department_name' => 'Строительный факультет'),
            array('id_department' => '157','department_name' => 'Студенческий городок'),
            array('id_department' => '177','department_name' => 'Студенческий профком'),
            array('id_department' => '150','department_name' => 'Техническое управление'),
            array('id_department' => '63','department_name' => 'Технологический факультет'),
            array('id_department' => '107','department_name' => 'Технопарк'),
            array('id_department' => '155','department_name' => 'Транспортный участок'),
            array('id_department' => '14','department_name' => 'Управление бухгалтерского учета'),
            array('id_department' => '17','department_name' => 'Управление мобилизационной подготовки, воинского учета и бронирования'),
            array('id_department' => '120','department_name' => 'Управление персоналом'),
            array('id_department' => '130','department_name' => 'Управление по взаимодействию с работодателями'),
            array('id_department' => '131','department_name' => 'Управление по взаимодействию с работодателями'),
            array('id_department' => '165','department_name' => 'Управление по имущественным отношениям'),
            array('id_department' => '91','department_name' => 'Управление по инновационной деятельности'),
            array('id_department' => '112','department_name' => 'Управление по научной работе'),
            array('id_department' => '88','department_name' => 'Управление учебно-производственной деятельности'),
            array('id_department' => '89','department_name' => 'Управление учебно-производственной деятельности'),
            array('id_department' => '147','department_name' => 'Учебно-методический кабинет истории университета'),
            array('id_department' => '31','department_name' => 'Учебно-методическое управление'),
            array('id_department' => '153','department_name' => 'Учебно-производственный центр'),
            array('id_department' => '90','department_name' => 'Учебно-производственный центр энергоэффективного машиностроения'),
            array('id_department' => '75','department_name' => 'Факультет геологии, горного и нефтегазового дела'),
            array('id_department' => '41','department_name' => 'Факультет инноватики и организации производства'),
            array('id_department' => '49','department_name' => 'Факультет информационных технологий и управления'),
            array('id_department' => '85','department_name' => 'Факультет открытого дистанционного обучения'),
            array('id_department' => '9','department_name' => 'Физические лица'),
            array('id_department' => '145','department_name' => 'Центр дополнительного образования детей и взрослых'),
            array('id_department' => '104','department_name' => 'Центр коллективного пользования "Диагностика и энергоэффективное электрооборудование"'),
            array('id_department' => '142','department_name' => 'Центр переподготовки и повышения квалификации преподователей высших и средних специальных учебных заведений'),
            array('id_department' => '143','department_name' => 'Центр переподготовки и повышения квалификации преподователей высших и средних специальных учебных заведений'),
            array('id_department' => '144','department_name' => 'Центр переподготовки и повышения квалификации преподователей высших и средних специальных учебных заведений'),
            array('id_department' => '163','department_name' => 'Центр развития ребенка детский сад № 60'),
            array('id_department' => '127','department_name' => 'Центр экспортного контроля'),
            array('id_department' => '152','department_name' => 'Центр энергоресурсо-сбережения'),
            array('id_department' => '154','department_name' => 'Эксплуатационно-ремонтный отдел'),
            array('id_department' => '71','department_name' => 'Электромеханический факультет'),
            array('id_department' => '67','department_name' => 'Энергетический факультет'),
            array('id_department' => '87','department_name' => 'Южно-Российский инжиниринговый центр машиностроения, автоматизации и энергоресурсосбережения'),
            array('id_department' => '146','department_name' => 'Южный центр дополнительного профессионального образования'),
            array('id_department' => '13','department_name' => 'Юридическое управление')
          );
        
        foreach ($department as $k) {
            DB::table('departments')->insert([
                'name' => $k['department_name'],
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ]);
        }
    }
}
